#!/bin/sh

# First, we need to take this action for all raw devices...
# For simplicity here, I have made the assumption that raw disk devices are
# /dev/hd* and /dev/sd* - that is partitons on all 

# Where should the zpool mount?  We wipe out any data already here.
MOUNTDIR=/var/lib/ceph

#echo "Mountdir is $MOUNTDIR"

#Not for touching.
RAWDISKS=""

for DISK in `ls /dev/{h,s}d* 2>/dev/null `
do
	if [[ -z "`blkid $DISK`" && 1 -eq `ls -1 ${DISK}* | wc -l` ]]
	then
		#found a raw disk
		RAWDISKS="${RAWDISKS} $DISK"
	fi
done

# Now add all the raw disks we found into a zpool (tanked, Ceph does the 
# redundancy)
echo Raw disks $RAWDISKS
if [ ! -z "$RAWDISKS" ]
then
	#rm -rf "$MOUNTDIR"
	#zpool create -m "$MOUNTDIR" -o failmode=panic ceph $RAWDISKS
	zpool create -o failmode=panic ceph $RAWDISKS
fi

#zfs create -V `zfs list -H -d 0 -o avail ceph` ceph/blkdev
zfs create -V $(( 512 * `df -P /ceph | tail -n 1 | awk '{ print $4 }'` )) ceph/blkdev
mkfs -t btrfs -L ceph /dev/zvol/ceph/blkdev
echo "LABEL=ceph	/var/lib/ceph	btrfs	defaults	0 0" >> /etc/fstab
